basePath: /
definitions:
  handlers.createPersonRequest:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
  handlers.updatePersonRequest:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
  models.Person:
    properties:
      age:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: RESTful API for managing people
  title: PeopleHub API
  version: "1.0"
paths:
  /people:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Person'
            type: array
      summary: List all people
    post:
      consumes:
      - application/json
      parameters:
      - description: Person JSON
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/handlers.createPersonRequest'
      produces:
      - text/plain
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Invalid
          schema:
            type: string
      summary: Add a new person
  /people/{id}:
    delete:
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Delete person by ID
    patch:
      consumes:
      - application/json
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated fields
        in: body
        name: update
        required: true
        schema:
          $ref: '#/definitions/handlers.updatePersonRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update person fields
  /people/search:
    get:
      parameters:
      - description: Name keyword
        in: query
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Person'
            type: array
      summary: Search people by name
  /people/stats:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Get total number of people
swagger: "2.0"
